package.json
=> ci(semantic-release): Fix semantic-release script

.eslintrc.js, package-lock.json, package.json, src/cli.js
=> chore(eslint): Add eslintrc

presets/webpack-frontend/clipped.config.js, presets/webpack-frontend/package-lock.json, presets/webpack-frontend/package.json
=> feat: Support for vue and react

presets/webpack-frontend/clipped.config.js, presets/webpack-frontend/package.json
=> fix(webpack-frontend): Fix style loaders not chained

generators/base/generators/app/index.js, generators/base/generators/app/templates/_clipped.config.js, generators/base/generators/app/templates/_package.json, generators/base/generators/app/templates/src/_index.js, generators/base/package-lock.json, generators/base/package.json, package-lock.json, package.json, presets/webpack-frontend/package.json, presets/webpack/clipped.config.js, src/instance/preset.js, yarn.lock
=> feat(hook): Add 'init' hook to scaffold using yeoman

README.md
=> Fix npm link in readme

presets/webpack-frontend/clipped.config.js, presets/webpack-frontend/package-lock.json, presets/webpack-frontend/package.json, presets/webpack-frontend/yarn.lock, presets/webpack/.eslintrc.js, presets/webpack/clipped.config.js, presets/webpack/package-lock.json, presets/webpack/package.json, presets/webpack/yarn.lock, src/instance/preset.js
=> feat(webpack): Handle more file types (image, font, audio)

presets/webpack-backend/clipped.config.js, presets/webpack-backend/package.json, presets/webpack-backend/yarn.lock, presets/webpack-frontend/docker-template/clipped.js, presets/webpack-frontend/package.json
=> feat: More hooks

.travis.yml, package.json, yarn.lock
=> build: Setup semantic-release-monorepo

packages/clipped/package.json, packages/clipped/src/instance/preset.js, yarn.lock
=> feat: copyTpl with clipped as context

.travis.yml, packages/clipped/clipped.config.js
=> fix(clipped): Fix using absolute path to source-map-support due to lerna

generators/base/package.json, packages/clipped/package.json, presets/docker/package.json, presets/webpack-backend/package.json, presets/webpack-frontend/package.json, presets/webpack-nodejs/package.json, presets/webpack/package.json, yarn.lock
=> chaos: calibrate versions of all packages

generators/base/package.json, presets/docker/package.json, presets/webpack-backend/package.json, presets/webpack-frontend/package.json, presets/webpack-nodejs/package.json, presets/webpack/package.json
=> feat: zero versions for all packages

.travis.yml
=> chaos: Ignore package version tags

.travis.yml, README.md, generators/base/package.json, presets/docker/package.json, presets/webpack-backend/package.json, presets/webpack-frontend/package.json, presets/webpack-nodejs/package.json, presets/webpack/package.json
=> chores: Reset to using autopublish

presets/webpack-backend/package.json, presets/webpack-nodejs/package.json, presets/webpack/clipped.config.js, presets/webpack/package.json, yarn.lock
=> fix: Watch hook exits on syntax error

packages/clipped/clipped.config.js, packages/clipped/package.json, packages/clipped/src/utils/miscellaneous.js, yarn.lock
=> refactor: Replace child_process with execa

packages/clipped/src/instance/preset.js
=> fix: Version hook using execa

packages/clipped/package.json, packages/clipped/src/instance/preset.js, presets/webpack-backend/package.json, presets/webpack-frontend/package.json, presets/webpack-nodejs/package.json, presets/webpack/clipped.config.js, presets/webpack/package.json, yarn.lock
=> feat: Make `clipped.config` jointed

.travis.yml, lerna.json, package.json, packages/clipped/package.json, presets/webpack-nodejs/clipped.config.js, presets/webpack-nodejs/package.json, presets/webpack/clipped.config.js, presets/webpack/package.json, yarn.lock
=> feat: Support `use` by bumping jointed version

packages/clipped/clipped.config.1.js, packages/clipped/package.json, yarn.lock
=> fix: Cannot get array element raw

.travis.yml
=> ci: Use new clipped

package.json, packages/clipped/clipped.config.js, packages/clipped/package.json, presets/webpack-backend/clipped.config.js, presets/webpack-backend/package.json, presets/webpack-frontend/clipped.config.js, presets/webpack-frontend/package.json, presets/webpack-nodejs/clipped.config.js, presets/webpack-nodejs/package.json, presets/webpack/clipped.config.js, presets/webpack/package.json, yarn.lock
=> fix: Preset followup

packages/clipped/package.json, packages/clipped/src/instance/preset.js, packages/clipped/src/utils/miscellaneous.js, yarn.lock
=> fix: remove execa

presets/docker/package.json, presets/webpack-backend/clipped.config.js, presets/webpack-backend/package.json, presets/webpack-frontend/clipped.config.js, presets/webpack-frontend/package.json, presets/webpack-nodejs/clipped.config.js, presets/webpack-nodejs/package.json, presets/webpack/clipped.config.js, presets/webpack/package.json
=> fix: Use scoped package for presets

packages/clipped/clipped.config.js
=> chaos: Use scoped preset in clipped itself

package.json, packages/clipped/package.json, presets/webpack-frontend/package.json, presets/webpack-nodejs/package.json, presets/webpack/clipped.config.js, presets/webpack/package.json
=> fix: Babel presets not added in webpack preset

.travis.yml
=> ci: Try lerna publish

.travis.yml
=> Revert "ci: Try lerna publish"

.travis.yml, presets/webpack-frontend/clipped.config.js, presets/webpack-frontend/package.json, presets/webpack/clipped.config.js
=> fix: Frontend preset not hot-reloading in dev hook

presets/webpack-frontend/clipped.config.js, presets/webpack-frontend/package.json, yarn.lock
=> feat: Postcss for frontend

.gitignore, package.json, packages/clipped/package.json, presets/webpack-frontend/clipped.config.js, presets/webpack-frontend/package.json, yarn.lock
=> chores: Conventional commit

package.json
=> chore(coverage): Submit coverage to codacy

package.json, packages/clipped/src/instance/helper.js, packages/clipped/src/instance/hook.js, packages/clipped/src/instance/preset.js, packages/clipped/test/cli.test.js, packages/clipped/test/helper.test.js, packages/clipped/test/preset.test.js, yarn.lock
=> refactor: Tidy base preset

generators/base/generators/app/index.js, generators/base/package.json, packages/clipped/package.json, packages/clipped/src/cli.js, packages/clipped/src/instance/preset.js, yarn.lock
=> refactor: Use cosmic to read first preset

README.md
=> fix: Jointed

packages/clipped/package.json, packages/clipped/src/instance/helper.js, presets/webpack-frontend/clipped.config.js, presets/webpack-frontend/package.json, yarn.lock
=> feat: Artzlogger for logging

packages/clipped/src/utils/git.js
=> fix: Git pull when fail clone, and yarn install

packages/clipped/src/utils/git.js
=> refactor: Use simple-git's pull

presets/webpack-frontend/package.json, presets/webpack-nodejs/package.json, presets/webpack/clipped.config.js, presets/webpack/package.json, yarn.lock
=> feat: Uglify js

packages/clipped/package.json, yarn.lock
=> fix: update jointed for multiple bug fixes

packages/clipped/package.json, presets/webpack4/base/clipped.config.js, presets/webpack4/base/package.json, presets/webpack4/frontend/clipped.config.js, presets/webpack4/frontend/docker-template/Dockerfile, presets/webpack4/frontend/docker-template/clipped.js, presets/webpack4/frontend/docker-template/package.json, presets/webpack4/frontend/package.json, yarn.lock
=> feat: sets up webpack frontend

presets/webpack4/library/clipped.config.js, presets/webpack4/library/package.json, yarn.lock
=> feat: sets up webpack4 library preset

presets/webpack4/base/clipped.config.js, presets/webpack4/base/package.json, presets/webpack4/frontend/clipped.config.js, presets/webpack4/frontend/package.json, yarn.lock
=> feat: pwa and html template support

presets/webpack4/frontend/clipped.config.js, presets/webpack4/frontend/package.json, yarn.lock
=> fix: not able to use chunkhash in output filename

presets/webpack4/frontend/clipped.config.js
=> feat: stylus support

presets/webpack4/frontend/package.json
=> fix(dependency): wrong path lol

presets/webpack4/base/clipped.config.js
=> fix(preset): disables webpackbar to fix circular json structure

presets/webpack4/frontend/package.json, yarn.lock
=> fix(preset): updates html-webpack-plugin for webpack4 frontend

package.json, yarn.lock
=> Greenkeeper/lerna 3.3.2

packages/clipped/src/cli.ts, packages/clipped/src/instance/defer.ts, packages/clipped/src/instance/hook.ts, packages/clipped/src/instance/index.ts, packages/clipped/src/instance/preset.ts, packages/clipped/test/preset.test.ts, plugins/rollup/clipped.config.js, plugins/webpack/clipped.config.js
=> feat(defer): defer config mutation to hook exe

packages/clipped/package.json, plugins/eslint/clipped.config.js, plugins/eslint/package.json, yarn.lock
=> ✨ adds eslint plugin

plugins/rollup/clipped.config.js, plugins/typescript/clipped.config.js, plugins/typescript/package.json, yarn.lock
=> feat(typescript): adds typescript plugin

examples/radi/clipped.config.js, examples/radi/package.json, examples/radi/src/App.radi, examples/radi/src/index.js, packages/clipped/src/cli.ts, packages/clipped/src/instance/defer.ts, packages/clipped/src/instance/preset.ts, plugins/webpack/clipped.config.js, templates/radi/clipped.config.js, templates/radi/package.json, templates/radi/template/App.radi, templates/radi/template/index.js, yarn.lock
=> Template radi

plugins/jest/clipped.config.js, plugins/jest/package.json, plugins/jest/transformer.js, yarn.lock
=> feat(jest): adds jest plugin

packages/clipped/src/cli.ts, packages/clipped/src/instance/index.ts, packages/clipped/src/instance/preset.ts, packages/clipped/typings/clipped/clipped.d.ts, plugins/babel/clipped.config.js, plugins/docker/clipped.config.js, plugins/eslint/clipped.config.js, plugins/jest/clipped.config.js, plugins/mdx/clipped.config.js, plugins/rollup/clipped.config.js, plugins/typescript/clipped.config.js, plugins/webpack/clipped.config.js
=> feat(plugin): adds plugin description function

README.md
=> doc: adds usthing badge

plugins/ncc/clipped.config.js, plugins/ncc/package.json, plugins/ncc/src/index.js, yarn.lock
=> feat(ncc): adds ncc plugin
